import { createServerFn } from "@tanstack/react-start";
import { requireAdmin } from "@/integrations/supabase/role-middleware";
import type { Database } from "@/integrations/supabase/types";

// Real clone provisioning. For 'fork' and 'template' methods, we actually
// create the GitHub repo via the App; for 'clone' (independent), we just
// register the row and let the operator wire up the repo manually.

type ProvisioningMethod = Database["public"]["Enums"]["provisioning_method"];

export type ProvisionCloneInput = {
  name: string;
  slug: string;
  method: ProvisioningMethod;
  targetOwner: string; // org/user that will own the new repo
  tags: string[];
  cloudflareEnabled: boolean;
  notes: string;
  moduleIds: string[];
  // Pricing tier the customer is on, and any add-ons bought on top of it.
  // Recorded at creation so entitlement reconciliation has a baseline to diff
  // against — without it, the first plan change looks like an initial sync and
  // cannot tell an upgrade from a downgrade.
  planSlug?: string | null;
  addonSlugs?: string[];
  // When true, this clone must run on its own dedicated Supabase backend.
  // The wizard enqueues backend provisioning immediately after; DB triggers
  // prevent the backend from being deleted while this flag is set.
  // (Audit finding #11.)
  isolatedTenant?: boolean;
  // Operator-assigned billing/tracking identity.
  billingUserId?: string | null;
  billingStripeCustomerId?: string | null;
  // Which hosting provider should build and serve this clone. `manual` records
  // that a person configures the target — the arrangement every clone in this
  // fleet has today — and is NOT the same as declining a deployment. Omitted
  // means "use whatever platform_hosting_config says".
  deploymentProvider?: "vercel" | "manual" | "none";
  // Optional operator-chosen name in the Aurixa zone. Omitted, the clone's slug
  // is used. Either way it goes through `allocateSubdomain`, so a reserved or
  // taken name is suffixed rather than rejected or silently duplicated.
  subdomain?: string | null;
  // Activation window for this clone's payment gate, in hours. Undefined uses
  // the platform default (prime_config.clone_gate_default_hours, 72); null
  // arms a gate with no deadline. Only ever consulted for a clone on a PAID
  // plan — `armGate` decides that, not the caller.
  gateGraceHours?: number | null;
  // Idempotency key for the whole provisioning attempt. Generated by the
  // wizard once per submit; a resubmit (double-click, network retry,
  // navigation-then-back) with the same key returns the existing clone row
  // instead of creating a second GitHub repo. (Audit finding #13.)
  idempotencyKey?: string | null;
};

export type ProvisionCloneResult =
  | { ok: true; cloneId: string; githubUrl: string | null; idempotent?: boolean }
  | { ok: false; error: string };

export const provisionClone = createServerFn({ method: "POST" })
  .middleware([requireAdmin])
  .inputValidator((input: ProvisionCloneInput) => {
    if (!input?.name?.trim()) throw new Error("name is required");
    if (!input?.slug?.trim()) throw new Error("slug is required");
    if (!input?.targetOwner?.trim()) throw new Error("targetOwner is required");
    if (!["fork", "template", "clone"].includes(input.method)) {
      throw new Error("invalid method");
    }
    const trim = (v: unknown) => (typeof v === "string" ? v.trim() : "");
    return {
      ...input,
      billingUserId: trim(input.billingUserId) || null,
      billingStripeCustomerId: trim(input.billingStripeCustomerId) || null,
      idempotencyKey: trim(input.idempotencyKey) || null,
    };
  })

  .handler(async ({ data, context }): Promise<ProvisionCloneResult> => {
    const { provisionCloneCore } = await import(
      /* @vite-ignore */ "@/lib/_server-shims/clone-provisioning.server"
    );
    return provisionCloneCore(context.supabase, context.userId, data);
  });
