import { createServerFn } from "@tanstack/react-start";
import { requireAdmin } from "@/integrations/supabase/role-middleware";
import type { Database } from "@/integrations/supabase/types";

// Real clone provisioning. For 'fork' and 'template' methods, we actually
// create the GitHub repo via the App; for 'clone' (independent), we just
// register the row and let the operator wire up the repo manually.

type ProvisioningMethod = Database["public"]["Enums"]["provisioning_method"];

export type ProvisionCloneInput = {
  name: string;
  slug: string;
  method: ProvisioningMethod;
  targetOwner: string; // org/user that will own the new repo
  tags: string[];
  cloudflareEnabled: boolean;
  notes: string;
  moduleIds: string[];
  // Pricing tier the customer is on, and any add-ons bought on top of it.
  // Recorded at creation so entitlement reconciliation has a baseline to diff
  // against — without it, the first plan change looks like an initial sync and
  // cannot tell an upgrade from a downgrade.
  planSlug?: string | null;
  addonSlugs?: string[];
  // When true, this clone must run on its own dedicated Supabase backend.
  // The wizard enqueues backend provisioning immediately after; DB triggers
  // prevent the backend from being deleted while this flag is set.
  // (Audit finding #11.)
  isolatedTenant?: boolean;
  // Operator-assigned billing/tracking identity.
  billingUserId?: string | null;
  billingStripeCustomerId?: string | null;
  // Which hosting provider should build and serve this clone. `manual` records
  // that a person configures the target — the arrangement every clone in this
  // fleet has today — and is NOT the same as declining a deployment. Omitted
  // means "use whatever platform_hosting_config says".
  deploymentProvider?: "vercel" | "manual" | "none";
  // Optional operator-chosen name in the Aurixa zone. Omitted, the clone's slug
  // is used. Either way it goes through `allocateSubdomain`, so a reserved or
  // taken name is suffixed rather than rejected or silently duplicated.
  subdomain?: string | null;
  // Activation window for this clone's payment gate, in hours. Undefined uses
  // the platform default (prime_config.clone_gate_default_hours, 72); null
  // arms a gate with no deadline. Only ever consulted for a clone on a PAID
  // plan — `armGate` decides that, not the caller.
  gateGraceHours?: number | null;
  /**
   * Provision this clone's own Supabase backend as part of creation.
   *
   * It used to be a SECOND call, made by the browser after this server
   * function had already returned. Nothing else creates a
   * `clone_backends` row — not the deployment drain, not a sweep — so a
   * submit interrupted in between (a closed tab, a dropped connection, a
   * Worker request limit) left a clone with a repository, a queued
   * deployment, `isolated_tenant: true` and no backend, for ever, with
   * nothing anywhere recording that one had been asked for. The admin
   * password went with the tab.
   *
   * Here instead, so the whole decision is taken in one transaction's worth
   * of work from one set of inputs. The password is on a SHORTER path than
   * it was, not a new one: it reaches the same queue, encrypted at rest by
   * `enqueueCloneBackendProvisioning`, and is cleared once the worker seeds
   * the admin user.
   */
  backend?: {
    region?: string;
    adminEmail: string;
    adminPassword: string;
  } | null;
  /**
   * The sending domain an operator typed for this clone's email identity.
   *
   * Carried because `advanceEmailIdentity` falls back to
   * `deriveSendingDomain(clone)` when it finds none recorded — so a browser
   * that never made the second call did not fail, it silently started an
   * identity on a domain nobody chose.
   */
  sendingDomain?: string | null;
  // Idempotency key for the whole provisioning attempt. Generated by the
  // wizard once per submit; a resubmit (double-click, network retry,
  // navigation-then-back) with the same key returns the existing clone row
  // instead of creating a second GitHub repo. (Audit finding #13.)
  idempotencyKey?: string | null;
};

export type ProvisionCloneResult =
  | {
      ok: true;
      cloneId: string;
      githubUrl: string | null;
      idempotent?: boolean;
      /**
       * The name this clone was actually given in the Aurixa zone, or null
       * where it was declined or could not be allocated.
       *
       * Returned rather than left for the caller to read back, because a
       * caller that reads it back is a caller that can disagree with it — and
       * the wizard reading its own guess instead of this answer is exactly the
       * defect `provisionCloneSubdomain` was written to end.
       */
      subdomainFqdn?: string | null;
    }
  | { ok: false; error: string };

export const provisionClone = createServerFn({ method: "POST" })
  .middleware([requireAdmin])
  .inputValidator((input: ProvisionCloneInput) => {
    if (!input?.name?.trim()) throw new Error("name is required");
    if (!input?.slug?.trim()) throw new Error("slug is required");
    if (!input?.targetOwner?.trim()) throw new Error("targetOwner is required");
    if (!["fork", "template", "clone"].includes(input.method)) {
      throw new Error("invalid method");
    }
    const trim = (v: unknown) => (typeof v === "string" ? v.trim() : "");
    // A backend asked for with no credentials is refused HERE rather than
    // enqueued and failed by a worker minutes later: the operator is still on
    // the page, and the queue's own validator says the same thing to nobody.
    if (input.backend) {
      if (!trim(input.backend.adminEmail)) throw new Error("backend.adminEmail is required");
      if ((input.backend.adminPassword ?? "").length < 8) {
        throw new Error("backend.adminPassword must be at least 8 characters");
      }
    }
    return {
      ...input,
      billingUserId: trim(input.billingUserId) || null,
      billingStripeCustomerId: trim(input.billingStripeCustomerId) || null,
      idempotencyKey: trim(input.idempotencyKey) || null,
    };
  })

  .handler(async ({ data, context }): Promise<ProvisionCloneResult> => {
    const { provisionCloneCore } = await import(
      /* @vite-ignore */ "@/lib/_server-shims/clone-provisioning.server"
    );
    return provisionCloneCore(context.supabase, context.userId, data);
  });
