/**
 * Whose object is this? — the question that made the surplus unactionable.
 *
 * ## What was stuck
 *
 * Catalog introspection creates and never drops, and every parity stage
 * reconciles on `clone >= prime` — containment, not equality. So an object the
 * prime DELETES survives on every clone for ever, and the engine reads that as
 * reconciled. Measured on the Preflight clone, 3 Sep 2026:
 * `public.builder_design_images`, present there and in no schema of the prime,
 * against a `tables` stage reporting reconciled. Parity now rolls the surplus
 * up and says it — and then stops, because:
 *
 * > Removing an object from a live tenant database destroys data if the object
 * > is theirs rather than the prime's leftover, and nothing in the schema
 * > distinguishes the two.
 *
 * The second half of that sentence was true of the SCHEMA and false of the
 * system. The prime's own migration history distinguishes them perfectly: if
 * the prime's migrations created an object, it was the prime's; if they never
 * mention it, it never was. `supabase/migration-object-index.json` in the
 * prime's repository is that history, generated by
 * `scripts/build-migration-object-index.mjs` and checked for staleness by the
 * prime's CI.
 *
 * It is the same rule the FILE cascade already applies — "a path is removed
 * only where prime's own history shows it deleted AND this clone's copy is
 * byte-identical to a version prime itself held" — expressed for the database.
 *
 * ## What this does and does not do
 *
 * It classifies. **It drops nothing, and nothing downstream drops on it.**
 * Dropping an object from a tenant's live database stays the owner's decision;
 * what changes is that the decision is now per-object and carries its
 * evidence, instead of being one unanswerable "537 tables against 536".
 *
 * ## The rules
 *
 * **Absent evidence is never permission.** A missing, unreadable or
 * older-schema index yields `undetermined` for everything, not
 * `never_the_primes` and not `prime_dropped`. The whole failure mode this
 * guards against is a confident answer from nothing, which this codebase has
 * already shipped once elsewhere.
 *
 * **The tenant's own object is the protected class.** `never_the_primes` is
 * the only verdict that is a claim about the tenant, and it is reached only by
 * a complete index that does not name the object. Everything uncertain lands
 * in `undetermined`, which is reviewed rather than acted on.
 *
 * **An explicit DROP is stronger than mere absence**, so it is carried
 * separately rather than folded in: the prime having deliberately dropped an
 * object is different evidence from the prime simply not having it now.
 */

export type SurplusVerdict =
  /** The prime's migrations created it and the prime does not have it now. */
  | "prime_dropped"
  /** The prime's migrations never mention it — it is the tenant's own. */
  | "never_the_primes"
  /** No usable index, so nothing is claimed either way. */
  | "undetermined";

export type MigrationObjectIndex = {
  schema_version: number;
  migration_files: number;
  created: readonly string[];
  dropped: readonly string[];
};

/** The index shape this classifier understands. A newer one is not assumed. */
export const SUPPORTED_INDEX_SCHEMA = 1;

export type SurplusClassification = {
  /** As parity reports it: `"tables:public.foo"`. */
  entry: string;
  objectClass: string;
  name: string;
  verdict: SurplusVerdict;
  /** True only where the prime's migrations carry an explicit DROP. */
  explicitlyDropped: boolean;
  /** One sentence a person reads. Never a bare identifier. */
  detail: string;
};

/**
 * Parity's class names are plural (`tables`, `functions`); the index's are
 * singular (`table:`, `function:`). Mapped rather than de-pluralised, because
 * a rule that guesses `matviews` → `matview` is a rule that silently stops
 * matching the day a class is added.
 */
const CLASS_TO_INDEX: Record<string, string> = {
  tables: "table",
  functions: "function",
  triggers: "trigger",
  indexes: "index",
  matviews: "materialized_view",
  sequences: "sequence",
  views: "view",
  types: "type",
};

/** Everything parity can report a surplus for that this index cannot judge. */
export const UNINDEXED_CLASSES = new Set(["edge_functions", "constraints"]);

function parseEntry(entry: string): { objectClass: string; name: string } {
  const at = entry.indexOf(":");
  if (at < 0) return { objectClass: "", name: entry.trim().toLowerCase() };
  return {
    objectClass: entry.slice(0, at).trim().toLowerCase(),
    name: entry
      .slice(at + 1)
      .trim()
      .replace(/"/g, "")
      .toLowerCase(),
  };
}

/**
 * Does the index name this object?
 *
 * Matched qualified AND bare, because the generator stores a name exactly as
 * the statement wrote it: `create table foo` records `foo` while parity
 * reports `public.foo`. Assuming `public` for an unqualified name would be
 * wrong about every other schema; matching the last segment as well is
 * WIDER, and wider here means "treat it as the prime's", which is the side
 * that gets reviewed rather than dropped.
 */
function indexNames(set: ReadonlySet<string>, objectClass: string, name: string): boolean {
  if (set.has(`${objectClass}:${name}`)) return true;
  const bare = name.includes(".") ? name.slice(name.lastIndexOf(".") + 1) : name;
  return set.has(`${objectClass}:${bare}`);
}

export function classifySurplus(
  entries: readonly string[],
  index: MigrationObjectIndex | null | undefined,
): SurplusClassification[] {
  const usable =
    !!index &&
    index.schema_version === SUPPORTED_INDEX_SCHEMA &&
    Array.isArray(index.created) &&
    index.created.length > 0;

  const created = new Set(usable ? index!.created : []);
  const dropped = new Set(usable ? index!.dropped : []);

  return entries.map((entry) => {
    const { objectClass, name } = parseEntry(entry);
    const indexClass = CLASS_TO_INDEX[objectClass];

    if (!usable) {
      return {
        entry,
        objectClass,
        name,
        verdict: "undetermined" as const,
        explicitlyDropped: false,
        detail:
          "The prime's migration object index could not be read, so whether this is the " +
          "prime's leftover or the tenant's own object is unknown. Nothing is claimed.",
      };
    }

    if (!indexClass || UNINDEXED_CLASSES.has(objectClass)) {
      return {
        entry,
        objectClass,
        name,
        verdict: "undetermined" as const,
        explicitlyDropped: false,
        detail:
          `The index does not cover ${objectClass || "this object class"}, so its origin ` +
          "is not decided here.",
      };
    }

    const wasCreated = indexNames(created, indexClass, name);
    const wasDropped = indexNames(dropped, indexClass, name);

    if (!wasCreated) {
      return {
        entry,
        objectClass,
        name,
        verdict: "never_the_primes" as const,
        explicitlyDropped: false,
        detail:
          `No migration in the prime's history creates ${name}, so it is the tenant's own. ` +
          "It must not be removed.",
      };
    }

    return {
      entry,
      objectClass,
      name,
      verdict: "prime_dropped" as const,
      explicitlyDropped: wasDropped,
      detail: wasDropped
        ? `The prime's migrations create ${name} and then drop it, and the prime does not ` +
          "have it now. It is the prime's leftover on this tenant."
        : `The prime's migrations create ${name} and the prime does not have it now, though ` +
          "no migration drops it explicitly. Probably the prime's leftover — confirm before acting.",
    };
  });
}

export type SurplusOriginSummary = {
  classified: SurplusClassification[];
  counts: Record<SurplusVerdict, number>;
  /** A line for the parity summary. Empty when there is no surplus. */
  line: string;
};

export function summariseSurplusOrigin(
  entries: readonly string[],
  index: MigrationObjectIndex | null | undefined,
): SurplusOriginSummary {
  const classified = classifySurplus(entries, index);
  const counts: Record<SurplusVerdict, number> = {
    prime_dropped: 0,
    never_the_primes: 0,
    undetermined: 0,
  };
  for (const c of classified) counts[c.verdict]++;

  if (classified.length === 0) return { classified, counts, line: "" };

  const parts: string[] = [];
  if (counts.prime_dropped) parts.push(`${counts.prime_dropped} the prime dropped`);
  if (counts.never_the_primes) parts.push(`${counts.never_the_primes} the tenant's own`);
  if (counts.undetermined) parts.push(`${counts.undetermined} undetermined`);

  return {
    classified,
    counts,
    // Says what it is and what it is not. A count beside the word "surplus"
    // reads as a to-do list; this one says nothing is being removed.
    line: `surplus origin: ${parts.join(", ")} — nothing is dropped on this reading`,
  };
}
