import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Build output, the Deno edge function (separate runtime, not the Vite app),
    // and large generated files that are regenerated by tooling.
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "supabase/functions/**",
      "**/routeTree.gen.ts",
      "src/integrations/supabase/types.ts",
      "src/vendor/**",
      // Held byte-identical to the prime's supabase/functions/_shared/marketing/
      // and pinned by MARKETING_ENGINE.lock.json, so it is formatted the
      // prime's way; marketingEngineLock.test.ts checks its bytes and purity,
      // and `tsc` still type-checks it here.
      "src/lib/marketing/engine/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // Tracked as warnings (visible, non-blocking) rather than off or error:
      // legacy `any` is being reduced incrementally (Phase 3 regenerates the DB
      // types), and surfacing unused vars/expressions flags dead code without
      // turning the lint gate red on day one.
      // `@ts-nocheck` is allowed only when it says why. A bare directive hides
      // every unrelated error in the file as well as the ones it was added for,
      // which is how 164 files came to be suppressing 1,038 errors — including
      // eight that were fatal at runtime. The set of files permitted to carry
      // one at all is frozen in scripts/ts-nocheck-budget.txt and only shrinks.
      "@typescript-eslint/ban-ts-comment": [
        "error",
        {
          "ts-nocheck": "allow-with-description",
          "ts-ignore": true,
          "ts-expect-error": "allow-with-description",
          minimumDescriptionLength: 20,
        },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-unused-expressions": "warn",
    },
  },
  {
    // Application code deploys to Cloudflare Workers, which forbids compiling
    // WebAssembly from bytes at runtime. libsodium-wrappers does exactly that
    // on first use, which silently broke every GitHub Actions secret sync
    // with `Aborted(CompileError: ... disallowed by embedder)`. It is kept as
    // a devDependency purely as the reference implementation that
    // github-sealed-box.server.test.ts checks our pure-JS sealed box against,
    // so importing it anywhere else is an error rather than a warning.
    files: ["**/*.{ts,tsx}"],
    ignores: ["**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "libsodium-wrappers",
              message:
                "libsodium-wrappers instantiates WebAssembly at runtime, which the Workers " +
                "runtime rejects. Use sealedBoxBase64 from @/server/github-sealed-box.server.",
            },
            {
              name: "libsodium",
              message:
                "libsodium instantiates WebAssembly at runtime, which the Workers runtime " +
                "rejects. Use sealedBoxBase64 from @/server/github-sealed-box.server.",
            },
          ],
        },
      ],
    },
  },
  {
    // Lovable regenerates this file and its header says so: "This file is
    // automatically generated. Do not edit it directly."
    //
    // It declares `timer` with `let` and assigns it once, which `prefer-const`
    // treats as an error. That has been fixed by hand TWICE (0d07dda, c7dc3e9)
    // and reverted by the generator both times — the flip-flop is visible in
    // `git log -L 38,38` on the file. Two hand-fixes and two reverts is a
    // settled pattern, not bad luck, and each revert turned an unrelated PR's
    // merge-ref CI red for a file nobody in this repository authored.
    //
    // Downgraded rather than ignored: the file is small and the rest of it is
    // worth linting, and a finding that is real should stay visible. What it
    // must not do is fail a gate on code we cannot keep fixed.
    files: ["src/integrations/supabase/previewAuthStorage.ts"],
    rules: { "prefer-const": "warn" },
  },
  eslintPluginPrettier,
  {
    // Keep format drift visible without blocking feature verification. The repo
    // already treats incremental cleanup findings as warnings, and routeTree plus
    // generated Supabase types are ignored above.
    rules: { "prettier/prettier": "warn" },
  },
);
