#!/usr/bin/env node
/**
 * Pins the marketing engine's bytes.
 *
 * The engine (`src/lib/marketing/engine/*.pure.ts`) is held byte-identical in
 * the prime, npc-property-dashbord (`supabase/functions/_shared/marketing/`). Each
 * repository records the sha256 of every engine file in
 * `MARKETING_ENGINE.lock.json`, and `marketingEngineLock.test.ts` fails when a
 * file no longer matches its line. The two lock files are the same file: an
 * engine change is finished when both repositories hold the new bytes and the
 * same `engineVersion`.
 *
 * Each digest sits under its own `sha256` key, never beside its filename. The
 * lock travels to every clone the prime's engine is cascaded to, and each
 * clone scans its own working tree with its own `.gitleaks.toml`, which the
 * cascade never delivers. `generic-api-key` reads a filename carrying `Api`
 * (`googleApi.pure.ts`) as a credential name and a digest on the same line as
 * its value, here too: the remediation workflow's secret-leak guard scans
 * this tree with the default rules. The shape has to pass every scanner as it
 * stands. `engineVersion` is computed from the names and digests alone, so
 * the shape does not move it.
 *
 *   node scripts/marketing/engine-lock.mjs           # rewrite the lock
 *   node scripts/marketing/engine-lock.mjs --check   # exit 1 on drift
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const ENGINE_DIR = join(ROOT, "src", "lib", "marketing", "engine");
const LOCK = join(ENGINE_DIR, "MARKETING_ENGINE.lock.json");

export function engineDigests(dir) {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".pure.ts"))
    .sort();
  const entries = Object.fromEntries(
    files.map((f) => [
      f,
      createHash("sha256")
        .update(readFileSync(join(dir, f)))
        .digest("hex"),
    ]),
  );
  const engineVersion = createHash("sha256")
    .update(files.map((f) => `${f}:${entries[f]}`).join("\n"))
    .digest("hex")
    .slice(0, 16);
  return {
    engineVersion,
    files: Object.fromEntries(files.map((f) => [f, { sha256: entries[f] }])),
  };
}

function render(lock) {
  return `${JSON.stringify(
    {
      $comment:
        "Generated by scripts/marketing/engine-lock.mjs. Byte-identical engine files are held in npc-property-dashbord (supabase/functions/_shared/marketing) and aurixa-mission-control (src/lib/marketing/engine); both repositories must carry this same lock.",
      ...lock,
    },
    null,
    2,
  )}\n`;
}

const lock = engineDigests(ENGINE_DIR);
const next = render(lock);
if (process.argv.includes("--check")) {
  const current = existsSync(LOCK) ? readFileSync(LOCK, "utf8") : "";
  if (current !== next) {
    console.error(
      "MARKETING_ENGINE.lock.json is stale. Run: node scripts/marketing/engine-lock.mjs",
    );
    process.exit(1);
  }
  console.log(
    `marketing engine ${lock.engineVersion}: ${Object.keys(lock.files).length} files match the lock`,
  );
} else {
  writeFileSync(LOCK, next);
  console.log(`wrote ${LOCK} (engine ${lock.engineVersion})`);
}
