-- ===========================================================================
-- The native mobile gateway and the mobile release registry.
--
-- @asserts table:clone_mobile_gateways
-- @asserts table:mobile_access_grants
-- @asserts table:mobile_activation_tickets
-- @asserts table:mobile_releases
-- @asserts table:mobile_release_rollouts
-- @asserts table:mobile_download_tickets
-- @asserts table:mobile_install_reports
-- @asserts table:clone_mobile_release_subscriptions
-- @asserts check:platform_hosting_config.reserved_slugs=mobile
--
-- No Aurixa app is listed on any public marketplace (the owner, 8 Oct 2026).
-- Every install and every update is handed out by Mission Control, and every
-- clone is connected to it from birth. This migration is the storage half of
-- that decision; npc-property-dashbord mobile/plan.md (Draft 03) is the whole.
--
-- ## Who may open which app: grants, keys and tickets
--
-- A GRANT is one principal of one clone allowed into one portal's app. Its
-- public reference (`grant_ref`, `mga_…`) appears in every link; its secret
-- half is generated by the app at its first claim and stored here only as a
-- hash, binding the grant to that installation. A TICKET is the single-use
-- thing a link actually carries — a magic link lives 15 minutes, a
-- provisioned URL 48 hours — and only its hash is stored. The ticket travels in
-- the URL fragment, so no server log ever holds it, and a GET of the link
-- consumes nothing: only the app's POST to the claim endpoint does, in one
-- conditional UPDATE.
--
-- ## The clone's own connection: clone_mobile_gateways
--
-- One row per clone, written at birth by step 5h of provisionCloneBackend and
-- converged for clones born earlier by the SAME function from the
-- clone-secrets reconcile sweep — so there is no second path that "injects"
-- the machinery, and no orphan. The row holds the clone mobile credential
-- (`mmc_…`) as a prefix and a SHA-256, the project ref it was delivered to, and
-- the portals the clone is licensed for.
--
-- ## Packages: mobile_releases and six private buckets
--
-- A release is a row; its package is an object in that portal's private
-- bucket, at {environment}/{platform}/{version}+{build}/{sha256}/artifact.
-- Packages are never bytea in a table. Nothing here is public: an install is a
-- one-time download ticket that Mission Control streams, and the app verifies
-- the signed manifest, the SHA-256 and the signing certificate before
-- installing anything.
--
-- ## Subscriptions
--
-- clone_mobile_release_subscriptions is one row per (clone, portal), written
-- at birth for all six portals. `enabled` says whether the clone may receive
-- that portal's releases; a portal the clone is not licensed for keeps its row
-- and is disabled, so licensing a portal later is a flag, not a birth.
--
-- Every table is read by operators and written only by the service role (the
-- server functions that own it). The buckets have no storage policy at all:
-- only the service role touches a package.
-- ===========================================================================

-- ─── clone_mobile_gateways ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.clone_mobile_gateways (
  clone_id UUID PRIMARY KEY REFERENCES public.clones(id) ON DELETE CASCADE,
  gateway_id TEXT NOT NULL UNIQUE,
  credential_prefix TEXT NOT NULL,
  credential_hash TEXT NOT NULL UNIQUE,
  delivered_project_ref TEXT,
  delivered_env_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'suspended', 'revoked')),
  licensed_portals TEXT[] NOT NULL DEFAULT ARRAY['command-centre']::text[],
  -- Draft 02 §11: native activation follows a 14 × 24-hour trial from THIS
  -- row's birth, plus extensions an operator authorised. A clone born before
  -- this table existed gets no retrial: it is admitted through a recorded,
  -- attributed exception instead (no gate backfill, no recharge).
  trial_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  trial_extension_hours INTEGER NOT NULL DEFAULT 0 CHECK (trial_extension_hours >= 0),
  cohort_enabled BOOLEAN NOT NULL DEFAULT true,
  legacy_clone BOOLEAN NOT NULL DEFAULT false,
  exception_granted_at TIMESTAMPTZ,
  exception_granted_by UUID,
  exception_reason TEXT,
  last_seen_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT clone_mobile_gateways_exception_attributed CHECK (
    exception_granted_at IS NULL
    OR (exception_granted_by IS NOT NULL AND length(coalesce(exception_reason, '')) >= 10)
  ),
  CONSTRAINT clone_mobile_gateways_portals_known CHECK (
    licensed_portals <@ ARRAY['command-centre','client','finance','solicitor','builder','accountant']::text[]
  )
);
ALTER TABLE public.clone_mobile_gateways ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read clone_mobile_gateways" ON public.clone_mobile_gateways;
CREATE POLICY "Operators read clone_mobile_gateways" ON public.clone_mobile_gateways
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── mobile_access_grants ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mobile_access_grants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  grant_ref TEXT NOT NULL UNIQUE,
  clone_id UUID NOT NULL REFERENCES public.clones(id) ON DELETE CASCADE,
  portal TEXT NOT NULL CHECK (
    portal IN ('command-centre','client','finance','solicitor','builder','accountant')
  ),
  principal_kind TEXT NOT NULL DEFAULT 'superadmin'
    CHECK (principal_kind IN ('superadmin','staff','partner','client')),
  -- The principal's id IN THE CLONE (custom_users.id for staff). Mission
  -- Control never reads the clone's users; it records the id provisioning
  -- itself seeded, or the one an operator typed.
  principal_ref TEXT NOT NULL,
  principal_email TEXT,
  status TEXT NOT NULL DEFAULT 'issuable'
    CHECK (status IN ('issuable','active','device_bound','revoked')),
  key_hash TEXT,
  device_install_id TEXT,
  device_thumbprint TEXT,
  bound_at TIMESTAMPTZ,
  last_claimed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoked_reason TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT mobile_access_grants_bound_has_device CHECK (
    status <> 'device_bound' OR (device_install_id IS NOT NULL AND key_hash IS NOT NULL)
  ),
  CONSTRAINT mobile_access_grants_revoked_has_time CHECK (
    status <> 'revoked' OR revoked_at IS NOT NULL
  )
);
CREATE INDEX IF NOT EXISTS idx_mobile_access_grants_clone
  ON public.mobile_access_grants(clone_id, portal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mobile_access_grants_live_principal
  ON public.mobile_access_grants(clone_id, portal, principal_ref)
  WHERE status <> 'revoked';
ALTER TABLE public.mobile_access_grants ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read mobile_access_grants" ON public.mobile_access_grants;
CREATE POLICY "Operators read mobile_access_grants" ON public.mobile_access_grants
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── mobile_activation_tickets ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mobile_activation_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  grant_id UUID NOT NULL REFERENCES public.mobile_access_grants(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('magic_link','provisioned_url')),
  ticket_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  consumed_install_id TEXT,
  assertion_jti TEXT UNIQUE,
  delivered_to_email TEXT,
  issued_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mobile_activation_tickets_grant
  ON public.mobile_activation_tickets(grant_id);
ALTER TABLE public.mobile_activation_tickets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read mobile_activation_tickets" ON public.mobile_activation_tickets;
CREATE POLICY "Operators read mobile_activation_tickets" ON public.mobile_activation_tickets
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── mobile_releases ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mobile_releases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  portal TEXT NOT NULL CHECK (
    portal IN ('command-centre','client','finance','solicitor','builder','accountant')
  ),
  platform TEXT NOT NULL CHECK (platform IN ('android','ios')),
  environment TEXT NOT NULL DEFAULT 'production'
    CHECK (environment IN ('production','staging')),
  channel TEXT NOT NULL DEFAULT 'stable' CHECK (channel IN ('stable','beta','internal')),
  version TEXT NOT NULL,
  build_number INTEGER NOT NULL CHECK (build_number > 0),
  source_sha TEXT NOT NULL,
  content_sha256 TEXT CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
  signing_cert_sha256 TEXT CHECK (signing_cert_sha256 IS NULL OR signing_cert_sha256 ~ '^[0-9a-f]{64}$'),
  size_bytes BIGINT CHECK (size_bytes IS NULL OR size_bytes > 0),
  min_os TEXT,
  min_supported_build INTEGER CHECK (min_supported_build IS NULL OR min_supported_build > 0),
  critical BOOLEAN NOT NULL DEFAULT false,
  release_notes TEXT,
  storage_bucket TEXT,
  storage_path TEXT,
  -- iOS packages are never stored or served here: the app is an Apple
  -- Business Manager Custom App and Apple delivers it. The row still governs
  -- the version and the minimum-version gate.
  apple_custom_app_url TEXT,
  state TEXT NOT NULL DEFAULT 'candidate'
    CHECK (state IN ('candidate','approved','promoted','paused','withdrawn')),
  uploaded_at TIMESTAMPTZ,
  approved_by UUID,
  approved_at TIMESTAMPTZ,
  promoted_at TIMESTAMPTZ,
  withdrawn_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT mobile_releases_unique_build
    UNIQUE (portal, platform, environment, channel, build_number),
  CONSTRAINT mobile_releases_android_has_package CHECK (
    platform <> 'android' OR state = 'candidate' OR state = 'withdrawn'
    OR (content_sha256 IS NOT NULL AND signing_cert_sha256 IS NOT NULL AND storage_path IS NOT NULL)
  ),
  CONSTRAINT mobile_releases_approval_recorded CHECK (
    state NOT IN ('approved','promoted','paused') OR approved_at IS NOT NULL
  )
);
ALTER TABLE public.mobile_releases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read mobile_releases" ON public.mobile_releases;
CREATE POLICY "Operators read mobile_releases" ON public.mobile_releases
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── mobile_release_rollouts ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mobile_release_rollouts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  release_id UUID NOT NULL UNIQUE REFERENCES public.mobile_releases(id) ON DELETE CASCADE,
  percentage INTEGER NOT NULL DEFAULT 0 CHECK (percentage BETWEEN 0 AND 100),
  paused_at TIMESTAMPTZ,
  pause_reason TEXT,
  started_by UUID,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.mobile_release_rollouts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read mobile_release_rollouts" ON public.mobile_release_rollouts;
CREATE POLICY "Operators read mobile_release_rollouts" ON public.mobile_release_rollouts
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── mobile_download_tickets ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mobile_download_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  release_id UUID NOT NULL REFERENCES public.mobile_releases(id) ON DELETE CASCADE,
  clone_id UUID REFERENCES public.clones(id) ON DELETE CASCADE,
  grant_id UUID REFERENCES public.mobile_access_grants(id) ON DELETE CASCADE,
  ticket_hash TEXT NOT NULL UNIQUE,
  install_id TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mobile_download_tickets_release
  ON public.mobile_download_tickets(release_id);
CREATE INDEX IF NOT EXISTS idx_mobile_download_tickets_clone
  ON public.mobile_download_tickets(clone_id);
CREATE INDEX IF NOT EXISTS idx_mobile_download_tickets_grant
  ON public.mobile_download_tickets(grant_id);
ALTER TABLE public.mobile_download_tickets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read mobile_download_tickets" ON public.mobile_download_tickets;
CREATE POLICY "Operators read mobile_download_tickets" ON public.mobile_download_tickets
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── mobile_install_reports ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.mobile_install_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  clone_id UUID NOT NULL REFERENCES public.clones(id) ON DELETE CASCADE,
  release_id UUID REFERENCES public.mobile_releases(id) ON DELETE SET NULL,
  portal TEXT NOT NULL,
  platform TEXT NOT NULL CHECK (platform IN ('android','ios')),
  install_id TEXT NOT NULL,
  build_number INTEGER NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('running','installed','failed','blocked')),
  detail TEXT,
  reported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mobile_install_reports_clone
  ON public.mobile_install_reports(clone_id, reported_at DESC);
CREATE INDEX IF NOT EXISTS idx_mobile_install_reports_release
  ON public.mobile_install_reports(release_id);
ALTER TABLE public.mobile_install_reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read mobile_install_reports" ON public.mobile_install_reports;
CREATE POLICY "Operators read mobile_install_reports" ON public.mobile_install_reports
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── clone_mobile_release_subscriptions ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.clone_mobile_release_subscriptions (
  clone_id UUID NOT NULL REFERENCES public.clones(id) ON DELETE CASCADE,
  portal TEXT NOT NULL CHECK (
    portal IN ('command-centre','client','finance','solicitor','builder','accountant')
  ),
  channel TEXT NOT NULL DEFAULT 'stable' CHECK (channel IN ('stable','beta','internal')),
  enabled BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (clone_id, portal)
);
ALTER TABLE public.clone_mobile_release_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Operators read clone_mobile_release_subscriptions"
  ON public.clone_mobile_release_subscriptions;
CREATE POLICY "Operators read clone_mobile_release_subscriptions"
  ON public.clone_mobile_release_subscriptions
  FOR SELECT TO authenticated USING (public.is_operator(auth.uid()));

-- ─── updated_at ─────────────────────────────────────────────────────────────
DROP TRIGGER IF EXISTS trg_clone_mobile_gateways_updated_at ON public.clone_mobile_gateways;
CREATE TRIGGER trg_clone_mobile_gateways_updated_at BEFORE UPDATE ON public.clone_mobile_gateways
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS trg_mobile_access_grants_updated_at ON public.mobile_access_grants;
CREATE TRIGGER trg_mobile_access_grants_updated_at BEFORE UPDATE ON public.mobile_access_grants
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS trg_mobile_releases_updated_at ON public.mobile_releases;
CREATE TRIGGER trg_mobile_releases_updated_at BEFORE UPDATE ON public.mobile_releases
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS trg_mobile_release_rollouts_updated_at ON public.mobile_release_rollouts;
CREATE TRIGGER trg_mobile_release_rollouts_updated_at BEFORE UPDATE ON public.mobile_release_rollouts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS trg_clone_mobile_release_subscriptions_updated_at
  ON public.clone_mobile_release_subscriptions;
CREATE TRIGGER trg_clone_mobile_release_subscriptions_updated_at
  BEFORE UPDATE ON public.clone_mobile_release_subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ─── six private package buckets ────────────────────────────────────────────
-- 200 MB: a release APK is ~30-60 MB; the ceiling is headroom, not a target.
-- No storage policy is created: only the service role reads or writes a
-- package, and a download is a one-time ticket Mission Control streams.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
SELECT b, b, false, 209715200,
       ARRAY['application/vnd.android.package-archive','application/octet-stream']
FROM unnest(ARRAY[
  'mobile-releases-command-centre',
  'mobile-releases-client',
  'mobile-releases-finance',
  'mobile-releases-solicitor',
  'mobile-releases-builder',
  'mobile-releases-accountant'
]) AS b
ON CONFLICT (id) DO UPDATE
  SET public = false,
      file_size_limit = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ─── reserve the gateway host ───────────────────────────────────────────────
-- mobile.aurixasystems.com.au is the gateway. 20260914120000's reasoning
-- applies unchanged: a host Aurixa owns is not a clones row, so only
-- reserved_slugs stops a customer claiming it. Both halves: the default for a
-- fresh install, the union for the row that exists.
ALTER TABLE public.platform_hosting_config
  ALTER COLUMN reserved_slugs SET DEFAULT array[
    'www','api','admin','app','mail','ftp','staging','dev','test','prod',
    'auth','portal','dashboard','status','docs','blog','cdn','assets','static',
    'mission-control','aurixa','root','ns1','ns2',
    'builders','builder','network','connect','partners',
    'mobile','apps','install','update'
  ];

UPDATE public.platform_hosting_config
SET reserved_slugs = (
      SELECT array(
        SELECT DISTINCT s
        FROM unnest(reserved_slugs || array['mobile','apps','install','update']) AS s
        ORDER BY s
      )
    ),
    updated_at = now()
WHERE singleton = true
  AND NOT (reserved_slugs @> array['mobile','apps','install','update']);
