-- @asserts rows:cascade_path_approvals>=1

-- THE SEPTEMBER UNBLOCK, RECORDED WHERE THE ENGINE READS.
--
-- Prime's builder-portal decommission left every clone holding files prime
-- deleted, and the freeze it caused is recorded in CASCADE_ON_MERGE.md ("The
-- September freeze"). The engine's two refusals — the bulk-deletion cap and
-- the manual_reconcile hold on src/App.tsx — each end in "a person has to
-- decide", and `cascade_path_approvals` is where the decision lives. The
-- owner instructed this unblock in writing on 16 Sep 2026; this migration is
-- that decision, versioned, applied through Mission Control's own lane, and
-- revocable like any other approval row.
--
-- ## What is approved, and on what evidence
--
-- **bulk_deletion — 442 paths, on all three clones.** Every path was
-- verified byte-identical to a blob prime itself held at that path, by a
-- full-history walk of prime's default branch (deeper than the engine's own
-- bounded probe, same rule: unmodified prime content is not work). The
-- three clones' clone-only trees converge on this exact set; the nine files
-- npc-client-dashboard genuinely owns (its isolation spec, its transfer
-- scripts) are NOT prime-history candidates and are not in it. An approval
-- is never evidence — each path still has to earn its delete verdict from
-- prime's history at cascade time, and a path something surviving still
-- imports is kept regardless (`withholdReferencedDeletions`).
--
-- **overwrite — src/App.tsx, on npc-test-76b3b3 and preflight-property-group
-- ONLY.** Their copies are hand-merged hybrids carrying no clone-authored
-- work — measured three lines from prime@a600b6b, every one of them prime's
-- own missing InternalToolingGuard change — so blob evidence cannot release
-- them and a person can. Prime's copy restores the /builder/* route the
-- cascaded test asserts, and gains the guard they are missing.
-- npc-client-dashboard is DELIBERATELY EXCLUDED: its App.tsx carries the
-- client-facing route gates that are the whole point of that mirror, and
-- overwriting it would expose internal tooling on a client's domain. Its
-- one-route reconcile stays a human edit, as the pull request asks.
--
-- ## The shape of the write
--
-- Attributed to the owner's operator account, found by email; if that
-- account is missing, the oldest account stands in (Mission Control's first
-- user is its owner). If NO user exists the seed stands down with a notice
-- rather than failing the lane — a halted migration queue costs more than a
-- pending approval, and the dry-run card can record the same decision by
-- hand. `ON CONFLICT DO NOTHING` keeps any approval an operator has already
-- recorded, including a revocation newer than this file.

DO $$
DECLARE
  approver uuid;
BEGIN
  SELECT id INTO approver FROM auth.users
    WHERE lower(email) = 'admin@aurixasystems.com.au' LIMIT 1;
  IF approver IS NULL THEN
    SELECT id INTO approver FROM auth.users ORDER BY created_at ASC LIMIT 1;
  END IF;
  IF approver IS NULL THEN
    RAISE NOTICE 'seed_september_unblock_approvals: no auth user to attribute the decision to — standing down; record it through the dry-run card instead';
    RETURN;
  END IF;

  CREATE TEMP TABLE _unblock_paths (path text PRIMARY KEY) ON COMMIT DROP;
  INSERT INTO _unblock_paths (path) VALUES
    ('.github/workflows/set-builder-stock-link-secrets.yml'),
    ('.github/workflows/set-builder-stock-pdf-worker-secrets.yml'),
    ('cloudflare/builder-stock-image-worker/.gitignore'),
    ('cloudflare/builder-stock-image-worker/README.md'),
    ('cloudflare/builder-stock-image-worker/src/index.ts'),
    ('cloudflare/builder-stock-image-worker/wrangler.jsonc'),
    ('cloudflare/builder-stock-pdf-worker/.gitignore'),
    ('cloudflare/builder-stock-pdf-worker/README.md'),
    ('cloudflare/builder-stock-pdf-worker/package-lock.json'),
    ('cloudflare/builder-stock-pdf-worker/package.json'),
    ('cloudflare/builder-stock-pdf-worker/src/index.ts'),
    ('cloudflare/builder-stock-pdf-worker/src/pdfElection.do.ts'),
    ('cloudflare/builder-stock-pdf-worker/wrangler.jsonc'),
    ('scripts/builder-portal/extraction-manifest.mjs'),
    ('scripts/builder-portal/local-db/00-supabase-bootstrap.sql'),
    ('scripts/builder-portal/local-db/01-upstream-fixture.sql'),
    ('scripts/builder-portal/local-db/02-network-standalone.sql'),
    ('scripts/builder-portal/local-db/generate-builder-types.mjs'),
    ('scripts/builder-portal/local-db/network-standalone-check.mjs'),
    ('scripts/builder-portal/local-db/reset.mjs'),
    ('scripts/builder-portal/local-db/verify-collaboration.mjs'),
    ('scripts/builder-portal/local-db/verify-construction.mjs'),
    ('scripts/builder-portal/local-db/verify-delivery.mjs'),
    ('scripts/builder-portal/local-db/verify-inventory.mjs'),
    ('scripts/builder-portal/local-db/verify-phase-1.mjs'),
    ('scripts/builder-portal/local-db/verify-phase-2.mjs'),
    ('scripts/builder-portal/local-db/verify-phase-3.mjs'),
    ('scripts/builder-portal/local-db/verify-release-control.mjs'),
    ('scripts/builder-portal/local-db/verify-transactions.mjs'),
    ('scripts/builder-portal/local-db/verify-workspace.mjs'),
    ('scripts/builder-portal/phase-0-inspection.mjs'),
    ('scripts/builder-portal/phase-0-reconciliation.sql'),
    ('scripts/builder-portal/security-check.mjs'),
    ('scripts/builder-stock/classify-brochure-page.ts'),
    ('scripts/security/check-cloudflare-worker-hardening.mjs'),
    ('src/components/admin/builder-portal/AdminBuilderCollaborationPanel.tsx'),
    ('src/components/admin/builder-portal/AdminBuilderConstructionPanel.tsx'),
    ('src/components/admin/builder-portal/AdminBuilderDeliveryPanel.tsx'),
    ('src/components/admin/builder-portal/AdminBuilderInventoryPanel.tsx'),
    ('src/components/admin/builder-portal/AdminBuilderProjectsPanel.tsx'),
    ('src/components/admin/builder-portal/AdminBuilderTransactionsPanel.tsx'),
    ('src/components/admin/builder-portal/AdminBuilderWorkspacePanel.tsx'),
    ('src/components/admin/builder-portal/BuilderMembershipDialog.tsx'),
    ('src/components/admin/builder-portal/BuilderMembershipPermissionsDialog.tsx'),
    ('src/components/admin/builder-portal/BuilderOrganisationDialog.tsx'),
    ('src/components/admin/builder-portal/BuilderOrganisationStatusDialog.tsx'),
    ('src/components/admin/builder-portal/BuilderUserDialog.tsx'),
    ('src/components/admin/builder-portal/BuilderUserSessionsDialog.tsx'),
    ('src/components/admin/builder-portal/accessTypes.ts'),
    ('src/components/admin/builder-portal/ui/BuilderAccessLifecycle.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderConfirmDialog.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderEmptyState.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderMembershipFormDialog.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderOrganisationFormDialog.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderPermissionsDialog.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderSearchField.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderStatCard.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderStatusBadge.tsx'),
    ('src/components/admin/builder-portal/ui/BuilderUserFormDialog.tsx'),
    ('src/components/builder-portal/BuilderAuthShell.tsx'),
    ('src/components/builder-portal/BuilderNotificationBell.tsx'),
    ('src/components/builder-portal/BuilderOnboardingTour.tsx'),
    ('src/components/builder-portal/BuilderOrganisationSettingsCard.tsx'),
    ('src/components/builder-portal/BuilderOrganisationSwitcher.tsx'),
    ('src/components/builder-portal/BuilderPortalLayout.tsx'),
    ('src/components/builder-portal/BuilderPortalProtectedRoute.tsx'),
    ('src/components/builder-portal/BuilderPortalShell.tsx'),
    ('src/components/builder-portal/BuilderPreferencesCard.tsx'),
    ('src/components/builder-portal/BuilderPropertyImage.tsx'),
    ('src/components/builder-portal/BuilderScopePicker.tsx'),
    ('src/components/builder-portal/BuilderStockFigures.tsx'),
    ('src/components/builder-portal/__tests__/builderStockFigures.spec.tsx'),
    ('src/components/builder-portal/ui/BuilderPortalMetricCard.tsx'),
    ('src/components/builder-portal/ui/BuilderPortalUserCard.tsx'),
    ('src/components/builder-portal/ui/BuilderSchedule.tsx'),
    ('src/components/builder-portal/ui/DimensionRail.tsx'),
    ('src/components/builder-portal/ui/TitleBlock.tsx'),
    ('src/components/builder-portal/ui/builderPortalUiMounted.spec.ts'),
    ('src/hooks/useBuilderPortalAuth.tsx'),
    ('src/lib/__tests__/builderPortalTabIdentity.test.ts'),
    ('src/lib/__tests__/builderPortalTenantCache.test.ts'),
    ('src/lib/__tests__/builderPortalTransport.test.ts'),
    ('src/lib/__tests__/builderStockAtomicPublication.test.ts'),
    ('src/lib/__tests__/builderStockAutoSourceDrain.test.ts'),
    ('src/lib/__tests__/builderStockAutomaticImages.test.ts'),
    ('src/lib/__tests__/builderStockBranchReopen.test.ts'),
    ('src/lib/__tests__/builderStockBrochureLinks.test.ts'),
    ('src/lib/__tests__/builderStockBudgetHandback.test.ts'),
    ('src/lib/__tests__/builderStockBuilderSuppliedImage.test.ts'),
    ('src/lib/__tests__/builderStockCanonicalIdentity.test.ts'),
    ('src/lib/__tests__/builderStockCleanSourcePrecedence.test.ts'),
    ('src/lib/__tests__/builderStockCloudflareWorker.test.ts'),
    ('src/lib/__tests__/builderStockCoverEmphasis.test.ts'),
    ('src/lib/__tests__/builderStockCoverIsAPhotograph.test.ts'),
    ('src/lib/__tests__/builderStockCoverResolution.test.ts'),
    ('src/lib/__tests__/builderStockCronGate.test.ts'),
    ('src/lib/__tests__/builderStockDecodeFidelity.test.ts'),
    ('src/lib/__tests__/builderStockDesignEvidence.test.ts'),
    ('src/lib/__tests__/builderStockDetectionResidue.test.ts'),
    ('src/lib/__tests__/builderStockDetectorGeometry.test.ts'),
    ('src/lib/__tests__/builderStockDocumentNotes.test.ts'),
    ('src/lib/__tests__/builderStockEnforcementRanking.test.ts'),
    ('src/lib/__tests__/builderStockExactSourceImage.test.ts'),
    ('src/lib/__tests__/builderStockFallbackDriver.test.ts'),
    ('src/lib/__tests__/builderStockFilledTemplateBrochure.test.ts'),
    ('src/lib/__tests__/builderStockGoogleSheetsSource.test.ts'),
    ('src/lib/__tests__/builderStockHtmlViewLinks.test.ts'),
    ('src/lib/__tests__/builderStockImageProgress.test.ts'),
    ('src/lib/__tests__/builderStockImageryInheritance.test.ts'),
    ('src/lib/__tests__/builderStockImportBoundary.test.ts'),
    ('src/lib/__tests__/builderStockImportHandoff.test.ts'),
    ('src/lib/__tests__/builderStockItemIndependentSettler.test.ts'),
    ('src/lib/__tests__/builderStockItemWorkClaim.test.ts'),
    ('src/lib/__tests__/builderStockLabelDesignation.test.ts'),
    ('src/lib/__tests__/builderStockLadderExhaustion.test.ts'),
    ('src/lib/__tests__/builderStockLadderGeneration.test.ts'),
    ('src/lib/__tests__/builderStockLinkRecovery.test.ts'),
    ('src/lib/__tests__/builderStockManualStatsLiveRow.test.ts'),
    ('src/lib/__tests__/builderStockMarketplaceEligibility.test.ts'),
    ('src/lib/__tests__/builderStockNormalise.test.ts'),
    ('src/lib/__tests__/builderStockNotion.test.ts'),
    ('src/lib/__tests__/builderStockNotionViewContract.test.ts'),
    ('src/lib/__tests__/builderStockOverlayClearance.test.ts'),
    ('src/lib/__tests__/builderStockOverlayInpaint.test.ts'),
    ('src/lib/__tests__/builderStockOversizedPhotoStreetViewGuard.test.ts'),
    ('src/lib/__tests__/builderStockOversizedRaster.test.ts'),
    ('src/lib/__tests__/builderStockPackageAttempt.test.ts'),
    ('src/lib/__tests__/builderStockPackageIdentity.test.ts'),
    ('src/lib/__tests__/builderStockPackageImages.test.ts'),
    ('src/lib/__tests__/builderStockPackageTieBreak.test.ts'),
    ('src/lib/__tests__/builderStockPdfDecodeSlot.test.ts'),
    ('src/lib/__tests__/builderStockPdfSourceImages.test.ts'),
    ('src/lib/__tests__/builderStockPdfWorker.test.ts'),
    ('src/lib/__tests__/builderStockPreviewSanitization.test.ts'),
    ('src/lib/__tests__/builderStockPrimaryImageRole.test.ts'),
    ('src/lib/__tests__/builderStockProvenanceTarget.test.ts'),
    ('src/lib/__tests__/builderStockRasterPump.test.ts'),
    ('src/lib/__tests__/builderStockReimportIdentity.test.ts'),
    ('src/lib/__tests__/builderStockRemoveProperty.test.ts'),
    ('src/lib/__tests__/builderStockRepairRegionSafety.test.ts'),
    ('src/lib/__tests__/builderStockRuntimeReopen.test.ts'),
    ('src/lib/__tests__/builderStockRuntimeVersion.test.ts'),
    ('src/lib/__tests__/builderStockSanitizationCarryForward.test.ts'),
    ('src/lib/__tests__/builderStockSanitizationOwnership.test.ts'),
    ('src/lib/__tests__/builderStockSanitizeOverlay.test.ts'),
    ('src/lib/__tests__/builderStockSerialWorker.test.ts'),
    ('src/lib/__tests__/builderStockSettlementLiveness.test.ts'),
    ('src/lib/__tests__/builderStockSettlementPhase.test.ts'),
    ('src/lib/__tests__/builderStockSettlementRecovery.test.ts'),
    ('src/lib/__tests__/builderStockSheetHyperlinks.test.ts'),
    ('src/lib/__tests__/builderStockSizeHeaders.test.ts'),
    ('src/lib/__tests__/builderStockSolePropertyAnchor.test.ts'),
    ('src/lib/__tests__/builderStockSourceAccessNotice.test.ts'),
    ('src/lib/__tests__/builderStockSourceBranches.test.ts'),
    ('src/lib/__tests__/builderStockSourceDeletion.test.ts'),
    ('src/lib/__tests__/builderStockSourceDiscovery.test.ts'),
    ('src/lib/__tests__/builderStockSourceImages.test.ts'),
    ('src/lib/__tests__/builderStockSpreadsheetColumns.test.ts'),
    ('src/lib/__tests__/builderStockStreetViewHeading.test.ts'),
    ('src/lib/__tests__/builderStockSuppliedEvidence.test.ts'),
    ('src/lib/__tests__/builderStockTenantIsolation.test.ts'),
    ('src/lib/__tests__/builderStockUnreadDocument.test.ts'),
    ('src/lib/__tests__/builderStockUploadCompletion.test.ts'),
    ('src/lib/__tests__/builderStockUploadContract.test.ts'),
    ('src/lib/__tests__/builderStockUploadedPackage.test.ts'),
    ('src/lib/__tests__/builderStockUploadedPackageIdentity.test.ts'),
    ('src/lib/__tests__/builderStockUrlSource.test.ts'),
    ('src/lib/__tests__/builderStockVerdictOutstanding.test.ts'),
    ('src/lib/__tests__/builderStockWebImageStore.test.ts'),
    ('src/lib/__tests__/builderStockWebVerifiedStatus.test.ts'),
    ('src/lib/__tests__/builderStockWrongPhotograph.test.ts'),
    ('src/lib/__tests__/fixtures/builderStockPictures.ts'),
    ('src/lib/__tests__/fixtures/vp8Encoder.ts'),
    ('src/lib/builderAccessTerms.ts'),
    ('src/lib/builderActingOrganisation.ts'),
    ('src/lib/builderCollaboration.ts'),
    ('src/lib/builderConstruction.ts'),
    ('src/lib/builderConstructionRail.pure.test.ts'),
    ('src/lib/builderConstructionRail.pure.ts'),
    ('src/lib/builderDelivery.ts'),
    ('src/lib/builderHiddenSections.pure.ts'),
    ('src/lib/builderHiddenSections.spec.ts'),
    ('src/lib/builderInventory.ts'),
    ('src/lib/builderPortal.ts'),
    ('src/lib/builderProjects.ts'),
    ('src/lib/builderQueries.ts'),
    ('src/lib/builderStockQueries.ts'),
    ('src/lib/builderTransactions.ts'),
    ('src/lib/builderWorkspace.ts'),
    ('src/pages/admin/BuilderPortalAdmin.tsx'),
    ('src/pages/builder/BuilderAcceptInvite.tsx'),
    ('src/pages/builder/BuilderActivity.tsx'),
    ('src/pages/builder/BuilderChangePassword.tsx'),
    ('src/pages/builder/BuilderCompliance.tsx'),
    ('src/pages/builder/BuilderConstruction.tsx'),
    ('src/pages/builder/BuilderConstructionDetail.tsx'),
    ('src/pages/builder/BuilderDashboard.tsx'),
    ('src/pages/builder/BuilderDeliveryDetail.tsx'),
    ('src/pages/builder/BuilderDocuments.tsx'),
    ('src/pages/builder/BuilderForgotPassword.tsx'),
    ('src/pages/builder/BuilderInventory.tsx'),
    ('src/pages/builder/BuilderLogin.tsx'),
    ('src/pages/builder/BuilderMessages.tsx'),
    ('src/pages/builder/BuilderNotifications.tsx'),
    ('src/pages/builder/BuilderOnboarding.tsx'),
    ('src/pages/builder/BuilderPipeline.tsx'),
    ('src/pages/builder/BuilderProjectDetail.tsx'),
    ('src/pages/builder/BuilderProjects.tsx'),
    ('src/pages/builder/BuilderResetPassword.tsx'),
    ('src/pages/builder/BuilderSectionWithdrawn.tsx'),
    ('src/pages/builder/BuilderSelectOrganisation.tsx'),
    ('src/pages/builder/BuilderSettings.tsx'),
    ('src/pages/builder/BuilderStockList.css'),
    ('src/pages/builder/BuilderStockList.tsx'),
    ('src/pages/builder/BuilderTasks.tsx'),
    ('src/pages/builder/BuilderTerms.tsx'),
    ('src/pages/builder/BuilderTransactionDetail.tsx'),
    ('src/pages/builder/BuilderTransactions.tsx'),
    ('src/pages/builder/BuilderUnitDetail.tsx'),
    ('src/pages/builder/__tests__/stockPlate.spec.tsx'),
    ('src/styles/__tests__/builderDraftingMounted.spec.ts'),
    ('src/styles/builder-drafting.css'),
    ('supabase/functions/_shared/builderCollaboration.ts'),
    ('supabase/functions/_shared/builderConstruction.ts'),
    ('supabase/functions/_shared/builderDelivery.ts'),
    ('supabase/functions/_shared/builderDocuments.ts'),
    ('supabase/functions/_shared/builderInventory.ts'),
    ('supabase/functions/_shared/builderPortalAuth.ts'),
    ('supabase/functions/_shared/builderProjects.ts'),
    ('supabase/functions/_shared/builderSessionToken.ts'),
    ('supabase/functions/_shared/builderSessions.ts'),
    ('supabase/functions/_shared/builderStock/assessSourceImage.ts'),
    ('supabase/functions/_shared/builderStock/attachBuilderImage.ts'),
    ('supabase/functions/_shared/builderStock/builderSuppliedImage.pure.ts'),
    ('supabase/functions/_shared/builderStock/canonicalIdentity.pure.ts'),
    ('supabase/functions/_shared/builderStock/documentAnchors.pure.ts'),
    ('supabase/functions/_shared/builderStock/drivePackage.pure.ts'),
    ('supabase/functions/_shared/builderStock/extract.ts'),
    ('supabase/functions/_shared/builderStock/fetchSource.ts'),
    ('supabase/functions/_shared/builderStock/googleSheetsHtmlGrid.pure.ts'),
    ('supabase/functions/_shared/builderStock/googleSheetsSource.pure.ts'),
    ('supabase/functions/_shared/builderStock/htmlSource.pure.ts'),
    ('supabase/functions/_shared/builderStock/imageProgress.pure.ts'),
    ('supabase/functions/_shared/builderStock/images.ts'),
    ('supabase/functions/_shared/builderStock/importStock.ts'),
    ('supabase/functions/_shared/builderStock/inpaintOverlay.pure.ts'),
    ('supabase/functions/_shared/builderStock/inpaintOverlay.ts'),
    ('supabase/functions/_shared/builderStock/itemWorkClaim.ts'),
    ('supabase/functions/_shared/builderStock/linkRecovery.pure.ts'),
    ('supabase/functions/_shared/builderStock/marketingOverlay.pure.ts'),
    ('supabase/functions/_shared/builderStock/modelExtract.ts'),
    ('supabase/functions/_shared/builderStock/negativeProvenance.pure.ts'),
    ('supabase/functions/_shared/builderStock/normalise.pure.ts'),
    ('supabase/functions/_shared/builderStock/notionPublicContent.ts'),
    ('supabase/functions/_shared/builderStock/notionRecordMap.pure.ts'),
    ('supabase/functions/_shared/builderStock/otherFormats.pure.ts'),
    ('supabase/functions/_shared/builderStock/overlayClearance.pure.ts'),
    ('supabase/functions/_shared/builderStock/overlayPlate.pure.ts'),
    ('supabase/functions/_shared/builderStock/packageAttempt.pure.ts'),
    ('supabase/functions/_shared/builderStock/packageImages.ts'),
    ('supabase/functions/_shared/builderStock/pdfDecodeSlot.pure.ts'),
    ('supabase/functions/_shared/builderStock/pdfElection.ts'),
    ('supabase/functions/_shared/builderStock/pdfElectionBoundary.pure.ts'),
    ('supabase/functions/_shared/builderStock/pdfElectionClient.ts'),
    ('supabase/functions/_shared/builderStock/pdfElectionRoute.pure.ts'),
    ('supabase/functions/_shared/builderStock/pdfFlattenedPhoto.pure.ts'),
    ('supabase/functions/_shared/builderStock/pdfPageImages.pure.ts'),
    ('supabase/functions/_shared/builderStock/pdfPrimaryImage.pure.ts'),
    ('supabase/functions/_shared/builderStock/pdfRowAnchors.pure.ts'),
    ('supabase/functions/_shared/builderStock/pdfSourcePhoto.ts'),
    ('supabase/functions/_shared/builderStock/pdfText.ts'),
    ('supabase/functions/_shared/builderStock/previewSanitization.ts'),
    ('supabase/functions/_shared/builderStock/provenanceVersion.pure.ts'),
    ('supabase/functions/_shared/builderStock/rasterPng.ts'),
    ('supabase/functions/_shared/builderStock/repairSourceImages.ts'),
    ('supabase/functions/_shared/builderStock/requestLinkRecovery.ts'),
    ('supabase/functions/_shared/builderStock/reverifyWebImages.ts'),
    ('supabase/functions/_shared/builderStock/runImport.ts'),
    ('supabase/functions/_shared/builderStock/runtimeVersion.pure.ts'),
    ('supabase/functions/_shared/builderStock/sanitizeImage.ts'),
    ('supabase/functions/_shared/builderStock/sanitizeOverlay.pure.ts'),
    ('supabase/functions/_shared/builderStock/settleFallbackImages.ts'),
    ('supabase/functions/_shared/builderStock/settleImageSanitization.ts'),
    ('supabase/functions/_shared/builderStock/settleItemImages.ts'),
    ('supabase/functions/_shared/builderStock/settleMarketplaceEligibility.ts'),
    ('supabase/functions/_shared/builderStock/settleSourceImages.ts'),
    ('supabase/functions/_shared/builderStock/settlementPhase.pure.ts'),
    ('supabase/functions/_shared/builderStock/sheetGrid.pure.ts'),
    ('supabase/functions/_shared/builderStock/sheetHyperlinks.pure.ts'),
    ('supabase/functions/_shared/builderStock/sourceAccessNotice.pure.ts'),
    ('supabase/functions/_shared/builderStock/sourceAssets.pure.ts'),
    ('supabase/functions/_shared/builderStock/sourceBranches.pure.ts'),
    ('supabase/functions/_shared/builderStock/sourceDeletion.pure.ts'),
    ('supabase/functions/_shared/builderStock/sourceImageRaster.ts'),
    ('supabase/functions/_shared/builderStock/sourceImageVision.pure.ts'),
    ('supabase/functions/_shared/builderStock/sourceImages.ts'),
    ('supabase/functions/_shared/builderStock/stockIdentity.pure.ts'),
    ('supabase/functions/_shared/builderStock/storedIdentityRepair.pure.ts'),
    ('supabase/functions/_shared/builderStock/streetViewHeading.pure.ts'),
    ('supabase/functions/_shared/builderStock/suppliedEvidence.pure.ts'),
    ('supabase/functions/_shared/builderStock/table.pure.ts'),
    ('supabase/functions/_shared/builderStock/uploadCompletion.ts'),
    ('supabase/functions/_shared/builderStock/urlSource.pure.ts'),
    ('supabase/functions/_shared/builderStock/vp8Tables.ts'),
    ('supabase/functions/_shared/builderStock/webImageIdentity.pure.ts'),
    ('supabase/functions/_shared/builderStock/webImageStore.ts'),
    ('supabase/functions/_shared/builderStock/webp.ts'),
    ('supabase/functions/_shared/builderStock/webpLossless.ts'),
    ('supabase/functions/_shared/builderStock/webpLossy.ts'),
    ('supabase/functions/_shared/builderStock/workbookSheets.ts'),
    ('supabase/functions/_shared/builderTransactions.ts'),
    ('supabase/functions/_shared/builderWorkspace.ts'),
    ('supabase/functions/builder-collaboration-admin/index.ts'),
    ('supabase/functions/builder-construction-admin/index.ts'),
    ('supabase/functions/builder-delivery-admin/index.ts'),
    ('supabase/functions/builder-document-processor/index.ts'),
    ('supabase/functions/builder-inventory-admin/index.ts'),
    ('supabase/functions/builder-portal-accept-invite/index.ts'),
    ('supabase/functions/builder-portal-admin/deno.json'),
    ('supabase/functions/builder-portal-admin/deno.lock'),
    ('supabase/functions/builder-portal-admin/index.ts'),
    ('supabase/functions/builder-portal-change-password/index.ts'),
    ('supabase/functions/builder-portal-collaboration/index.ts'),
    ('supabase/functions/builder-portal-construction/index.ts'),
    ('supabase/functions/builder-portal-delivery/index.ts'),
    ('supabase/functions/builder-portal-forgot-password/index.ts'),
    ('supabase/functions/builder-portal-inventory/index.ts'),
    ('supabase/functions/builder-portal-invite/index.ts'),
    ('supabase/functions/builder-portal-login/index.ts'),
    ('supabase/functions/builder-portal-logout/index.ts'),
    ('supabase/functions/builder-portal-projects/index.ts'),
    ('supabase/functions/builder-portal-reset-password/index.ts'),
    ('supabase/functions/builder-portal-stock/index.ts'),
    ('supabase/functions/builder-portal-transactions/index.ts'),
    ('supabase/functions/builder-portal-verify/index.ts'),
    ('supabase/functions/builder-portal-workspace/index.ts'),
    ('supabase/functions/builder-projects-admin/index.ts'),
    ('supabase/functions/builder-stock-image-settler/index.ts'),
    ('supabase/functions/builder-stock-link-callback/index.ts'),
    ('supabase/functions/builder-transactions-admin/index.ts'),
    ('supabase/functions/builder-workspace-admin/index.ts'),
    ('supabase/migrations/20260801000000_builder_portal_phase1_organisations_users.sql'),
    ('supabase/migrations/20260801000100_builder_portal_phase1_permissions.sql'),
    ('supabase/migrations/20260801000200_builder_portal_phase1_sessions.sql'),
    ('supabase/migrations/20260801000500_builder_portal_admin_module.sql'),
    ('supabase/migrations/20260801000600_builder_portal_activity_log.sql'),
    ('supabase/migrations/20260802000000_builder_portal_phase2_auth_governance.sql'),
    ('supabase/migrations/20260803000000_builder_portal_phase3_projects.sql'),
    ('supabase/migrations/20260803100620_b29948a7-0675-4a0a-8b38-82eb609c09d7.sql'),
    ('supabase/migrations/20260803105927_efc3ec8e-0931-4f65-86a7-5a329c5a9aec.sql'),
    ('supabase/migrations/20260803110130_f1da7c7d-4bc5-463d-8b0a-628c3d9629e9.sql'),
    ('supabase/migrations/20260803110353_8b8905b4-1c2e-4c29-a719-fbb8ef7a35f2.sql'),
    ('supabase/migrations/20260803110554_45db55bd-2e4b-4d23-8357-ed3c41bd40c3.sql'),
    ('supabase/migrations/20260803111221_362c9bd0-5891-4f34-9666-b0b112d17030.sql'),
    ('supabase/migrations/20260803111511_3a7d6693-7ee1-4174-bccb-18164f980a38.sql'),
    ('supabase/migrations/20260803111627_2cd43ffc-7e46-47d3-a68b-97b283c867b3.sql'),
    ('supabase/migrations/20260803113541_0e0936e9-23ee-4cf6-ba3c-ba87ac48a263.sql'),
    ('supabase/migrations/20260803130020_54682e8c-c768-44ea-8986-0c89416fff27.sql'),
    ('supabase/migrations/20260804000000_builder_portal_inventory.sql'),
    ('supabase/migrations/20260805000000_builder_portal_transactions.sql'),
    ('supabase/migrations/20260806000000_builder_portal_construction.sql'),
    ('supabase/migrations/20260807000000_builder_portal_delivery.sql'),
    ('supabase/migrations/20260808000000_builder_portal_collaboration.sql'),
    ('supabase/migrations/20260809000000_builder_portal_workspace.sql'),
    ('supabase/migrations/20260810000100_builder_portal_onboarding_tour.sql'),
    ('supabase/migrations/20260810000200_builder_document_quarantine_scanning.sql'),
    ('supabase/migrations/20260816130000_builder_stock_uploads_bootstrap.sql'),
    ('supabase/migrations/20260816140000_builder_stock_source_image_settlement.sql'),
    ('supabase/migrations/20260818120000_builder_stock_marketplace_eligibility_settlement.sql'),
    ('supabase/migrations/20260819090000_builder_stock_eligibility_target_version.sql'),
    ('supabase/migrations/20260820000000_builder_admin_safe_deletion.sql'),
    ('supabase/migrations/20260821000000_builder_admin_blocker_array_fix.sql'),
    ('supabase/migrations/20260822000000_builder_deletion_lifecycle.sql'),
    ('supabase/migrations/20260823000000_builder_deletion_audit_constraints.sql'),
    ('supabase/migrations/20260915000000_builder_stock_list_marketplace.sql'),
    ('supabase/migrations/20260916000000_builder_stock_url_sources_and_deletion.sql'),
    ('supabase/migrations/20260922000000_builder_stock_terminal_negative_provenance.sql'),
    ('supabase/migrations/20260925000000_builder_stock_image_sanitization_settlement.sql'),
    ('supabase/migrations/20260926000000_builder_stock_overlay_clearance.sql'),
    ('supabase/migrations/20260927000000_builder_stock_eligibility_v2.sql'),
    ('supabase/migrations/20261005000000_builder_stock_cron_gate_fallback.sql'),
    ('supabase/migrations/20261012000000_builder_stock_auto_source_drain.sql'),
    ('supabase/migrations/20261019000000_builder_stock_item_work_claim.sql'),
    ('supabase/migrations/20261021000000_builder_stock_item_work_claim_amendments.sql'),
    ('supabase/migrations/20261022000000_builder_stock_safe_publication.sql'),
    ('supabase/migrations/20261023000000_builder_stock_arm_on_upload.sql'),
    ('supabase/migrations/20261024000000_builder_stock_settler_fanout.sql'),
    ('supabase/migrations/20261025000000_builder_stock_publish_sweep.sql'),
    ('supabase/migrations/20261026000000_builder_stock_reopen_stranded.sql'),
    ('supabase/migrations/20261027010000_builder_stock_ladder_generation.sql'),
    ('supabase/migrations/20261028000000_builder_stock_retire_unbuilt_streetview.sql'),
    ('supabase/migrations/20261029000000_builder_stock_web_verified_status.sql'),
    ('supabase/migrations/20261030000000_builder_stock_link_recovery.sql'),
    ('supabase/migrations/20261102000000_builder_design_images.sql'),
    ('supabase/migrations/20261103000000_builder_stock_rearm_on_requeue.sql'),
    ('supabase/migrations/20261104000000_builder_stock_withdraw_design_renders.sql'),
    ('supabase/migrations/20261105000000_builder_stock_reopen_at_v9.sql'),
    ('supabase/migrations/20261106000000_builder_stock_reopen_at_v10.sql'),
    ('supabase/migrations/20261107000000_builder_stock_reopen_at_v11.sql'),
    ('supabase/migrations/20261108000000_builder_stock_reopen_at_v12.sql'),
    ('supabase/migrations/20261109000000_builder_stock_upload_completion_liveness.sql'),
    ('supabase/migrations/20261110000000_builder_stock_reopen_at_v13.sql'),
    ('supabase/migrations/20261111000000_builder_stock_package_uniqueness.sql'),
    ('supabase/migrations/20261111010000_builder_stock_reopen_at_v14.sql'),
    ('supabase/migrations/20261113110000_builder_stock_runtime_reopen.sql'),
    ('supabase/migrations/20261113110001_builder_stock_settler_fixed_concurrency.sql'),
    ('supabase/migrations/20261113120000_builder_stock_runtime_version_2.sql'),
    ('supabase/migrations/20261115100000_builder_stock_runtime_version_3.sql'),
    ('supabase/migrations/20261119130000_builder_stock_provenance_target.sql'),
    ('supabase/migrations/20261119170000_builder_stock_manual_stats.sql'),
    ('tests-e2e/builder-portal/collaboration.e2e.ts'),
    ('tests-e2e/builder-portal/construction.e2e.ts'),
    ('tests-e2e/builder-portal/delivery.e2e.ts'),
    ('tests-e2e/builder-portal/inventory.e2e.ts'),
    ('tests-e2e/builder-portal/onboarding-tour.e2e.ts'),
    ('tests-e2e/builder-portal/phase2-portal-shell.e2e.ts'),
    ('tests-e2e/builder-portal/phase3-projects.e2e.ts'),
    ('tests-e2e/builder-portal/transactions.e2e.ts'),
    ('tests-e2e/builder-portal/workspace.e2e.ts'),
    ('tests/builder-portal/admin-controls.test.mjs'),
    ('tests/builder-portal/admin-navigation.test.mjs'),
    ('tests/builder-portal/builder-access-flow.test.mjs'),
    ('tests/builder-portal/collaboration.test.mjs'),
    ('tests/builder-portal/construction.test.mjs'),
    ('tests/builder-portal/deletion-lifecycle.test.mjs'),
    ('tests/builder-portal/delivery.test.mjs'),
    ('tests/builder-portal/fixtures/phase-0-scenarios.json'),
    ('tests/builder-portal/inventory.test.mjs'),
    ('tests/builder-portal/onboarding-tour.test.mjs'),
    ('tests/builder-portal/organisation-dialog-layout.test.mjs'),
    ('tests/builder-portal/phase0-builder-domain-boundaries.test.mjs'),
    ('tests/builder-portal/phase0-existing-architecture.test.mjs'),
    ('tests/builder-portal/phase0-shared-primitive-constraints.test.mjs'),
    ('tests/builder-portal/phase1-identity-access.test.mjs'),
    ('tests/builder-portal/phase2-auth-governance.test.mjs'),
    ('tests/builder-portal/phase3-projects.test.mjs'),
    ('tests/builder-portal/portal-presentation.test.mjs'),
    ('tests/builder-portal/release-control.test.mjs'),
    ('tests/builder-portal/removal-refusal.test.mjs'),
    ('tests/builder-portal/transactions.test.mjs'),
    ('tests/builder-portal/workspace.test.mjs'),
    ('tsconfig.worker.json');

  INSERT INTO public.cascade_path_approvals
    (clone_id, kind, path, reason, approved_by, expires_at)
  SELECT c.id, 'bulk_deletion', p.path,
    'Builder-portal decommission deletion debt: every path verified byte-identical to a version prime itself held (full-history blob match, 16 Sep 2026). Recorded from the owner''s written unblock instruction; see migration 20260916100000.',
    approver, now() + interval '14 days'
  FROM public.clones c
  CROSS JOIN _unblock_paths p
  WHERE c.github_repo IN ('npc-test-76b3b3', 'preflight-property-group', 'npc-client-dashboard')
  ON CONFLICT (clone_id, kind, path) DO NOTHING;

  INSERT INTO public.cascade_path_approvals
    (clone_id, kind, path, reason, approved_by, expires_at)
  SELECT c.id, 'overwrite', 'src/App.tsx',
    'Hand-merged hybrid carrying no clone-authored work (three lines from prime@a600b6b, all prime''s own missing InternalToolingGuard change). Prime''s copy restores the /builder/* route and the guard. npc-client-dashboard deliberately excluded: its copy carries real client-facing gates. Owner-instructed unblock, 16 Sep 2026; see migration 20260916100000.',
    approver, now() + interval '14 days'
  FROM public.clones c
  WHERE c.github_repo IN ('npc-test-76b3b3', 'preflight-property-group')
  ON CONFLICT (clone_id, kind, path) DO NOTHING;
END $$;
